pipeline {
    agent any 

    triggers {
        githubPush()  // 💥 This triggers the build on push events from GitHub
    }

    environment {
        TOOL_DIR = "${WORKSPACE}\\ci-cd-tools"
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Build') { 
            steps {
                echo 'Explore Build Stage'
                bat "\"${TOOL_DIR}\\build.bat\" \"${WORKSPACE}\\Debug\" Debug all"
                // bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Debug Debug all" // original from Gene
                // bat "${TOOL_DIR}\\build.bat ${WORKSPACE}\\Release Release all"
            }
        }
        // stage('Static Code Analysis') {
        //     steps {
        //         catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
        //             bat "\"${TOOL_DIR}\\static-analysis.bat\" \"${WORKSPACE}\\App\""
                    
        //         }
        //     }
        // }
        stage('Flash-Debug') { 
            steps {
                // bat "${TOOL_DIR}\\flash.bat $params.DUT_STLINK_sn ${WORKSPACE}\\Debug\\CICDBadweh.bin"
                bat "\"${TOOL_DIR}\\flash.bat\" \"${params.DUT_STLINK_sn}\" \"${WORKSPACE}\\Debug\\tmphm_CICD.bin\""

            }
        }

        // stage('Debug Variables') {
        //     steps { 
        //         bat "echo BUILD_TAG=${BUILD_TAG}"
        //     }
        // }

        // stage('Test-Release') { 
        //     steps {
        //         bat "python3 ${TOOL_DIR}\\base-hilt.py --dut-serial=$params.DUT_console --sim-serial=$params.SIM_console --tver=${BUILD_TAG}-Release --jfile=test-results-release.xml"
        //         junit 'test-results-release.xml'
        //         bat "${TOOL_DIR}\\check-test-results.bat test-results-release.xml"
        //     }
        // }
        // stage('Test-Release') { 
        //     steps {
        //         bat "python \"${TOOL_DIR}\\base-hilt.py\" --dut-serial=${params.DUT_console} --sim-serial=none --tver=\"${BUILD_TAG}-Release\" --jfile=\"test-results-release.xml\""
        //         junit 'test-results-release.xml'



        //     }
        // }
       

    }
}
